# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        ('camo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camo_operation',
            name='pdt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.PDT', verbose_name='Powiązany PDT'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camo.Aircraft'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camo.ATA'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camo.Part'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='super_ass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camo.Assignment'),
        ),
    ]
