# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camo', '0101_auto_20160625_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='test',
            field=models.BooleanField(default=True, verbose_name='Test'),
        ),
    ]
