# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camo', '0102_aircraft_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='test',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Informacje dla pilotów'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='scheduled',
            field=models.BooleanField(default=True, verbose_name='Podlega rezerwacjom'),
        ),
    ]
