# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camo', '0103_auto_20161106_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='Kolor wyświetlania',
            field=models.CharField(default='#ccffcc', max_length=7),
        ),
    ]
