# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camo', '0104_aircraft_kolor wyswietlania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='Kolor wyświetlania',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='color',
            field=models.CharField(default='#ccffcc', max_length=7, verbose_name='Kolor wyświetlania'),
        ),
    ]
