# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camo', '0105_auto_20161118_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
    ]
