# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camo', '0106_auto_20170613_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='arc_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Wa\xc5\xbcno\xc5\x9b\xc4\x87 ARC'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='color',
            field=models.CharField(default=b'#ccffcc', max_length=7, verbose_name=b'Kolor wy\xc5\x9bwietlania'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='fuel_consumption',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name=b'Zu\xc5\xbcycie paliwa (L/h)'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='fuel_volume',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name=b'Szacowana ilo\xc5\x9b\xc4\x87 paliwa (L)'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='helicopter',
            field=models.BooleanField(default=False, verbose_name=b'\xc5\x9amig\xc5\x82owiec'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name=b'Informacje dla pilot\xc3\xb3w'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='insurance_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Wa\xc5\xbcno\xc5\x9b\xc4\x87 ubezp.'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='landings_count',
            field=models.IntegerField(default=0, verbose_name=b'Suma l\xc4\x85dowa\xc5\x84'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='ms_landings',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'MS do l\xc4\x85dowa\xc5\x84'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='radio_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Wa\xc5\xbcno\xc5\x9b\xc4\x87 radia'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.CharField(choices=[(b'flying', b'W u\xc5\xbcytkowaniu'), (b'damaged', b'Uszkodzony'), (b'parked', b'Zaparkowany')], max_length=10, verbose_name=b'Status u\xc5\xbcytkowania'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='use_cycles',
            field=models.BooleanField(default=False, verbose_name=b'U\xc5\xbcywaj cykli'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='use_landings',
            field=models.BooleanField(default=False, verbose_name=b'U\xc5\xbcywaj l\xc4\x85dowa\xc5\x84'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='wb_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Wa\xc5\xbcno\xc5\x9b\xc4\x87 W&B'),
        ),
        migrations.AlterField(
            model_name='ata',
            name='chapter',
            field=models.CharField(max_length=5, verbose_name=b'Rozdzia\xc5\x82'),
        ),
        migrations.AlterField(
            model_name='ata',
            name='chapter_title',
            field=models.CharField(max_length=100, verbose_name=b'Tytu\xc5\x82 rozdzia\xc5\x82u'),
        ),
        migrations.AlterField(
            model_name='ata',
            name='section_title',
            field=models.CharField(max_length=100, verbose_name=b'Tytu\xc5\x82 sekcji'),
        ),
        migrations.AlterField(
            model_name='camo_operation',
            name='landings',
            field=models.IntegerField(default=0, verbose_name=b'Liczba l\xc4\x85dowa\xc5\x84'),
        ),
        migrations.AlterField(
            model_name='camo_operation',
            name='pdt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.PDT', verbose_name=b'Powi\xc4\x85zany PDT'),
        ),
        migrations.AlterField(
            model_name='camo_operation',
            name='tth_end',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name=b'Licznik ko\xc5\x84cowy'),
        ),
        migrations.AlterField(
            model_name='camo_operation',
            name='tth_start',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name=b'Licznik pocz\xc4\x85tkowy'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='done_landings',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'L\xc4\x85dowania wykonania'),
        ),
        migrations.AlterField(
            model_name='ms_report',
            name='done_landings',
            field=models.IntegerField(default=0, verbose_name=b'Liczba l\xc4\x85dowa\xc5\x84'),
        ),
        migrations.AlterField(
            model_name='ms_report',
            name='fuselage',
            field=models.CharField(max_length=30, verbose_name=b'Numer p\xc5\x82atowca'),
        ),
        migrations.AlterField(
            model_name='ms_report',
            name='next_cycles',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Wa\xc5\xbcne do liczby cykli'),
        ),
        migrations.AlterField(
            model_name='ms_report',
            name='next_date',
            field=models.DateField(verbose_name=b'Wa\xc5\xbcne do daty'),
        ),
        migrations.AlterField(
            model_name='ms_report',
            name='next_hours',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name=b'Wa\xc5\xbcne do nalotu'),
        ),
        migrations.AlterField(
            model_name='ms_report',
            name='next_landings',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Wa\xc5\xbcne do liczby l\xc4\x85dowa\xc5\x84'),
        ),
        migrations.AlterField(
            model_name='part',
            name='landings_count',
            field=models.IntegerField(default=0, verbose_name=b'Suma l\xc4\x85dowa\xc5\x84'),
        ),
        migrations.AlterField(
            model_name='part',
            name='lifecycle',
            field=models.CharField(choices=[(b'llp', b'Ograniczona \xc5\xbcywotno\xc5\x9b\xc4\x87 (LLP)'), (b'ovh', b'Podlegaj\xc4\x85ca remontowi (OVH)'), (b'oth', b'Wed\xc5\x82ug stanu')], default=b'oth', max_length=10, verbose_name=b'Cykl \xc5\xbcycia'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_no',
            field=models.CharField(max_length=35, verbose_name=b'Numer cz\xc4\x99\xc5\x9bci (typ)'),
        ),
        migrations.AlterField(
            model_name='pot_event',
            name='done_landings',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Wykonano (l\xc4\x85dowania)'),
        ),
        migrations.AlterField(
            model_name='pot_event',
            name='name',
            field=models.TextField(verbose_name=b'Nazwa czynno\xc5\x9bci'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='adsb_agency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Organ wydaj\xc4\x85cy'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='adsb_related',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Powi\xc4\x85zanie AD/SB'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='applies',
            field=models.BooleanField(default=True, verbose_name=b'Dotyczy danej cz\xc4\x99\xc5\x9bci'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='count_type',
            field=models.CharField(choices=[(b'production', b'Od produkcji/remontu'), (b'install', b'Od instalacji')], default=b'production', max_length=10, verbose_name=b'Spos\xc3\xb3b liczenia'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='cyclic',
            field=models.BooleanField(default=True, verbose_name=b'Czynno\xc5\x9b\xc4\x87 cykliczna'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='done_landings',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Wykonano (l\xc4\x85dowania)'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='due_landings',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Limit l\xc4\x85dowa\xc5\x84'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='due_months',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Limit miesi\xc4\x99cy'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='optional',
            field=models.BooleanField(default=False, verbose_name=b'Czynno\xc5\x9b\xc4\x87 opcjonalna'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='parked',
            field=models.BooleanField(default=False, verbose_name=b'Czynno\xc5\x9b\xc4\x87 postojowa'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camo.Part', verbose_name=b'Powi\xc4\x85zana cz\xc4\x99\xc5\x9b\xc4\x87'),
        ),
        migrations.AlterField(
            model_name='pot_group',
            name='type',
            field=models.CharField(choices=[(b'oth', b'Obs\xc5\x82uga techniczna'), (b'llp', b'Planowy demonta\xc5\xbc'), (b'ovh', b'Planowy remont'), (b'ad', b'AD - Dyrektywa'), (b'sb', b'SB - Biuletyn')], default=b'oth', max_length=10, verbose_name=b'Rodzaj czynno\xc5\x9bci'),
        ),
        migrations.AlterField(
            model_name='wb_report',
            name='done_landings',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'L\xc4\x85dowania wykonania'),
        ),
    ]
