# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.BooleanField()),
            ],
            options={
                'permissions': [('sms_reader', 'SMS - Dostęp do odczytu'), ('sms_ncr', 'SMS - Dostęp do NCR'), ('sms_admin', 'SMS - Dostęp pełny')],
            },
        ),
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_scope', models.CharField(choices=[('AOC', 'AOC'), ('SPO', 'SPO'), ('CAMO', 'CAMO'), ('ATO', 'ATO')], max_length=10, verbose_name='Obszar audytu')),
                ('audit_type', models.CharField(choices=[('Wewnętrzny', 'Wewnętrzny'), ('Zewnętrzny', 'Zewnętrzny')], max_length=10, verbose_name='Rodzaj audytu')),
                ('audit_nbr', models.CharField(max_length=30, verbose_name='Numer audytu')),
                ('audit_date', models.DateField(verbose_name='Data audytu')),
                ('ncr_nbr', models.IntegerField(verbose_name='Numer NCR')),
                ('description', models.TextField(verbose_name='Treść NCR')),
                ('due_date', models.DateField(verbose_name='Wyznaczona data usunięcia')),
                ('done_date', models.DateField(blank=True, null=True, verbose_name='Data usunięcia')),
                ('check_date', models.DateField(blank=True, null=True, verbose_name='Data audytu sprawdzającego')),
            ],
        ),
        migrations.CreateModel(
            name='SMSEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(max_length=10, verbose_name='Statek powietrzny')),
                ('pic', models.CharField(max_length=40, verbose_name='Pilot dowódca')),
                ('event_date', models.DateField(verbose_name='Data zdarzenia')),
                ('oper_type', models.CharField(choices=[('AOC', 'AOC'), ('ATO', 'ATO'), ('Wynajem', 'Wynajem'), ('Prywatny', 'Prywatny'), ('Inne', 'Inne')], max_length=10, verbose_name='Rodzaj operacji')),
                ('event_type', models.CharField(choices=[('Zdarzenie', 'Zdarzenie'), ('Incydent', 'Incydent'), ('Poważny incydent', 'Powazny Incydent'), ('Wypadek', 'Wypadek')], max_length=20, verbose_name='Kwalifikacja zdarzenia')),
                ('pkbwl_ref', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numer ewidencyjny PKBWL')),
                ('pkbwl_date', models.DateField(blank=True, null=True, verbose_name='Data przyjęcia w PKBWL')),
                ('examiner', models.CharField(blank=True, max_length=50, null=True, verbose_name='Badający zdarzenie')),
                ('description', models.TextField(verbose_name='Opis zdarzenia')),
                ('scrutiny', models.TextField(blank=True, null=True, verbose_name='Przebieg badania wewnętrznego')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='Wnioski i zalecenia po badaniu wewnętrznym')),
                ('closure', models.CharField(blank=True, max_length=30, null=True, verbose_name='Zamknięcie badania / raport końcowy')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.FBOUser', verbose_name='Zgłaszający użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='SMSFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(max_length=10, verbose_name='Statek powietrzny')),
                ('person', models.CharField(blank=True, max_length=30, null=True, verbose_name='Osoba zgłaszająca')),
                ('failure_date', models.DateField(verbose_name='Data zgłoszenia')),
                ('description', models.TextField(verbose_name='Opis usterki')),
                ('repair_date', models.DateField(blank=True, null=True, verbose_name='Data usunięcia usterki')),
                ('repair_desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sposób usunięcia usterki')),
                ('crs', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer CRS')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='Wnioski i zalecenia ogólne')),
                ('pdt_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.PDT', verbose_name='Numer PDT')),
            ],
        ),
        migrations.CreateModel(
            name='SMSHazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(choices=[('Zewnętrzne', 'Zewnętrzne'), ('Osobowe', 'Osobowe'), ('Operacyjne', 'Operacyjne'), ('Techniczne', 'Techniczne'), ('AS 350', 'AS 350'), ('Inne', 'Inne')], max_length=10, verbose_name='Klasa zagrożenia')),
                ('hazard_ref', models.CharField(max_length=10, verbose_name='Identyfikator zagrożenia')),
                ('hazard_date', models.DateField(verbose_name='Data wprowadzenia')),
            ],
        ),
        migrations.CreateModel(
            name='SMSHazardRev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_num', models.IntegerField(default=1, verbose_name='Numer wersji')),
                ('rev_date', models.DateField(verbose_name='Data wersji')),
                ('rev_last', models.BooleanField(default=True, verbose_name='Aktualna wersja')),
                ('company_area', models.CharField(choices=[('SALT', 'SALT'), ('ATO', 'ATO'), ('AOC', 'AOC'), ('SPO', 'SPO'), ('Inne', 'Inne')], max_length=10, verbose_name='Obszar firmy')),
                ('name', models.TextField(verbose_name='Nazwa zagrożenia')),
                ('due_date', models.CharField(blank=True, max_length=30, null=True, verbose_name='Termin wykonania')),
                ('responsible', models.CharField(blank=True, max_length=50, null=True, verbose_name='Osoba odpowiedzialna')),
                ('control', models.TextField(blank=True, null=True, verbose_name='Wykonanie / kontrola')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.SMSHazard', verbose_name='Zarejestrowane zagrożenie')),
            ],
        ),
        migrations.CreateModel(
            name='SMSReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Data zgłoszenia')),
                ('person', models.CharField(blank=True, max_length=50, null=True, verbose_name='Osoba zgłaszająca')),
                ('privacy', models.BooleanField(default=False, verbose_name='Proszę o zachowanie poufnosci')),
                ('description', models.TextField(verbose_name='Treść zgłoszenia')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='Wnioski i zalecenia')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.FBOUser', verbose_name='Zgłoszajacy użytkownik')),
                ('smshazard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.SMSHazard', verbose_name='Zagrożenie w rejestrze')),
            ],
        ),
        migrations.CreateModel(
            name='SMSRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_ref', models.CharField(max_length=10, verbose_name='Identyfikator ryzyka')),
                ('rev_num', models.IntegerField(default=1, verbose_name='Numer wersji')),
                ('rev_date', models.DateField(verbose_name='Data wersji')),
                ('rev_last', models.BooleanField(default=True, verbose_name='Aktualna wersja')),
                ('description', models.TextField(verbose_name='Szczegółowy opis natury ryzyka')),
                ('init_probability', models.CharField(choices=[('5', '5 - Bardzo wysokie'), ('4', '4 - Wysokie'), ('3', '3 - Średnie'), ('2', '2 - Niskie'), ('1', '1 - Bardzo niskie')], max_length=1, verbose_name='Początkowe prawdopodobieństwo')),
                ('init_impact', models.CharField(choices=[('E', 'E - Bardzo duża'), ('D', 'D - Duża'), ('C', 'C - Średnia'), ('B', 'B - Mała'), ('A', 'A - Bardzo mała')], max_length=1, verbose_name='Początkowa dotkliwość')),
                ('mitigation', models.TextField(blank=True, null=True, verbose_name='Sposoby ograniczania ryzyka')),
                ('res_probability', models.CharField(blank=True, choices=[('5', '5 - Bardzo wysokie'), ('4', '4 - Wysokie'), ('3', '3 - Średnie'), ('2', '2 - Niskie'), ('1', '1 - Bardzo niskie')], max_length=1, null=True, verbose_name='Szczątkowe prawdopodobieństwo')),
                ('res_impact', models.CharField(blank=True, choices=[('E', 'E - Bardzo duża'), ('D', 'D - Duża'), ('C', 'C - Średnia'), ('B', 'B - Mała'), ('A', 'A - Bardzo mała')], max_length=1, null=True, verbose_name='Szczątkowa dotkliwość')),
                ('smshazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.SMSHazard', verbose_name='Zarejestrowane zagrożenie')),
            ],
        ),
        migrations.AddField(
            model_name='smsfailure',
            name='smshazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.SMSHazard', verbose_name='Zagrożenie w rejestrze'),
        ),
        migrations.AddField(
            model_name='smsevent',
            name='smshazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.SMSHazard', verbose_name='Zagrożenie w rejestrze'),
        ),
    ]
