# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20170807_2101'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncr',
            name='ncr_user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_user1_set', to='panel.FBOUser', verbose_name='Osoba odpowiedzialna 1'),
        ),
        migrations.AddField(
            model_name='ncr',
            name='ncr_user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_user2_set', to='panel.FBOUser', verbose_name='Osoba odpowiedzialna 2'),
        ),
    ]
