# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20170807_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='smshazard',
            name='hazard_active',
            field=models.BooleanField(default=True, verbose_name='Aktywne'),
        ),
    ]
