# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0024_auto_20160901_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsevent',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.FBOUser', verbose_name='Zgłaszający użytkownik'),
        ),
        migrations.AlterField(
            model_name='smsevent',
            name='smshazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.SMSHazard', verbose_name='Zagrożenie w rejestrze'),
        ),
        migrations.AlterField(
            model_name='smsfailure',
            name='pdt_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.PDT', verbose_name='Numer PDT'),
        ),
        migrations.AlterField(
            model_name='smsfailure',
            name='smshazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.SMSHazard', verbose_name='Zagrożenie w rejestrze'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.FBOUser', verbose_name='Zgłoszajacy użytkownik'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='smshazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.SMSHazard', verbose_name='Zagrożenie w rejestrze'),
        ),
    ]
