# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0054_auto_20170806_1604'),
        ('sms', '0026_auto_20170613_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncr',
            name='ncr_user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_user1_set', to='panel.FBOUser', verbose_name='Osoba odpowiedzialna 1'),
        ),
        migrations.AddField(
            model_name='ncr',
            name='ncr_user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_user2_set', to='panel.FBOUser', verbose_name='Osoba odpowiedzialna 2'),
        ),
    ]
