# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-29 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0027_auto_20170806_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='smshazard',
            name='hazard_active',
            field=models.BooleanField(default=True, verbose_name='Aktywne'),
        ),
    ]
