# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0028_smshazard_hazard_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncr',
            name='audit_type',
            field=models.CharField(choices=[(b'Wewn\xc4\x99trzny', b'Wewn\xc4\x99trzny'), (b'Zewn\xc4\x99trzny', b'Zewn\xc4\x99trzny')], max_length=10, verbose_name=b'Rodzaj audytu'),
        ),
        migrations.AlterField(
            model_name='ncr',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Data audytu sprawdzaj\xc4\x85cego'),
        ),
        migrations.AlterField(
            model_name='ncr',
            name='description',
            field=models.TextField(verbose_name=b'Tre\xc5\x9b\xc4\x87 NCR'),
        ),
        migrations.AlterField(
            model_name='ncr',
            name='done_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Data usuni\xc4\x99cia'),
        ),
        migrations.AlterField(
            model_name='ncr',
            name='due_date',
            field=models.DateField(verbose_name=b'Wyznaczona data usuni\xc4\x99cia'),
        ),
        migrations.AlterField(
            model_name='smsevent',
            name='closure',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Zamkni\xc4\x99cie badania / raport ko\xc5\x84cowy'),
        ),
        migrations.AlterField(
            model_name='smsevent',
            name='event_type',
            field=models.CharField(choices=[(b'Zdarzenie', b'Zdarzenie'), (b'Incydent', b'Incydent'), (b'Powa\xc5\xbcny incydent', b'Powazny Incydent'), (b'Wypadek', b'Wypadek')], max_length=20, verbose_name=b'Kwalifikacja zdarzenia'),
        ),
        migrations.AlterField(
            model_name='smsevent',
            name='examiner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Badaj\xc4\x85cy zdarzenie'),
        ),
        migrations.AlterField(
            model_name='smsevent',
            name='findings',
            field=models.TextField(blank=True, null=True, verbose_name=b'Wnioski i zalecenia po badaniu wewn\xc4\x99trznym'),
        ),
        migrations.AlterField(
            model_name='smsevent',
            name='pic',
            field=models.CharField(max_length=40, verbose_name=b'Pilot dow\xc3\xb3dca'),
        ),
        migrations.AlterField(
            model_name='smsevent',
            name='pkbwl_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Data przyj\xc4\x99cia w PKBWL'),
        ),
        migrations.AlterField(
            model_name='smsevent',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.FBOUser', verbose_name=b'Zg\xc5\x82aszaj\xc4\x85cy u\xc5\xbcytkownik'),
        ),
        migrations.AlterField(
            model_name='smsevent',
            name='scrutiny',
            field=models.TextField(blank=True, null=True, verbose_name=b'Przebieg badania wewn\xc4\x99trznego'),
        ),
        migrations.AlterField(
            model_name='smsevent',
            name='smshazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.SMSHazard', verbose_name=b'Zagro\xc5\xbcenie w rejestrze'),
        ),
        migrations.AlterField(
            model_name='smsfailure',
            name='failure_date',
            field=models.DateField(verbose_name=b'Data zg\xc5\x82oszenia'),
        ),
        migrations.AlterField(
            model_name='smsfailure',
            name='findings',
            field=models.TextField(blank=True, null=True, verbose_name=b'Wnioski i zalecenia og\xc3\xb3lne'),
        ),
        migrations.AlterField(
            model_name='smsfailure',
            name='person',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Osoba zg\xc5\x82aszaj\xc4\x85ca'),
        ),
        migrations.AlterField(
            model_name='smsfailure',
            name='repair_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Data usuni\xc4\x99cia usterki'),
        ),
        migrations.AlterField(
            model_name='smsfailure',
            name='repair_desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Spos\xc3\xb3b usuni\xc4\x99cia usterki'),
        ),
        migrations.AlterField(
            model_name='smsfailure',
            name='smshazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.SMSHazard', verbose_name=b'Zagro\xc5\xbcenie w rejestrze'),
        ),
        migrations.AlterField(
            model_name='smshazard',
            name='hazard_ref',
            field=models.CharField(max_length=10, verbose_name=b'Identyfikator zagro\xc5\xbcenia'),
        ),
        migrations.AlterField(
            model_name='smshazard',
            name='hazard_type',
            field=models.CharField(choices=[(b'Zewn\xc4\x99trzne', b'Zewn\xc4\x99trzne'), (b'Osobowe', b'Osobowe'), (b'Operacyjne', b'Operacyjne'), (b'Techniczne', b'Techniczne'), (b'AS 350', b'AS 350'), (b'Inne', b'Inne')], max_length=10, verbose_name=b'Klasa zagro\xc5\xbcenia'),
        ),
        migrations.AlterField(
            model_name='smshazardrev',
            name='hazard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.SMSHazard', verbose_name=b'Zarejestrowane zagro\xc5\xbcenie'),
        ),
        migrations.AlterField(
            model_name='smshazardrev',
            name='name',
            field=models.TextField(verbose_name=b'Nazwa zagro\xc5\xbcenia'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='description',
            field=models.TextField(verbose_name=b'Tre\xc5\x9b\xc4\x87 zg\xc5\x82oszenia'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Osoba zg\xc5\x82aszaj\xc4\x85ca'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name=b'Prosz\xc4\x99 o zachowanie poufnosci'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='report_date',
            field=models.DateField(verbose_name=b'Data zg\xc5\x82oszenia'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.FBOUser', verbose_name=b'Zg\xc5\x82oszajacy u\xc5\xbcytkownik'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='smshazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.SMSHazard', verbose_name=b'Zagro\xc5\xbcenie w rejestrze'),
        ),
        migrations.AlterField(
            model_name='smsrisk',
            name='description',
            field=models.TextField(verbose_name=b'Szczeg\xc3\xb3\xc5\x82owy opis natury ryzyka'),
        ),
        migrations.AlterField(
            model_name='smsrisk',
            name='init_impact',
            field=models.CharField(choices=[(b'E', b'E - Bardzo du\xc5\xbca'), (b'D', b'D - Du\xc5\xbca'), (b'C', b'C - \xc5\x9arednia'), (b'B', b'B - Ma\xc5\x82a'), (b'A', b'A - Bardzo ma\xc5\x82a')], max_length=1, verbose_name=b'Pocz\xc4\x85tkowa dotkliwo\xc5\x9b\xc4\x87'),
        ),
        migrations.AlterField(
            model_name='smsrisk',
            name='init_probability',
            field=models.CharField(choices=[(b'5', b'5 - Bardzo wysokie'), (b'4', b'4 - Wysokie'), (b'3', b'3 - \xc5\x9arednie'), (b'2', b'2 - Niskie'), (b'1', b'1 - Bardzo niskie')], max_length=1, verbose_name=b'Pocz\xc4\x85tkowe prawdopodobie\xc5\x84stwo'),
        ),
        migrations.AlterField(
            model_name='smsrisk',
            name='res_impact',
            field=models.CharField(blank=True, choices=[(b'E', b'E - Bardzo du\xc5\xbca'), (b'D', b'D - Du\xc5\xbca'), (b'C', b'C - \xc5\x9arednia'), (b'B', b'B - Ma\xc5\x82a'), (b'A', b'A - Bardzo ma\xc5\x82a')], max_length=1, null=True, verbose_name=b'Szcz\xc4\x85tkowa dotkliwo\xc5\x9b\xc4\x87'),
        ),
        migrations.AlterField(
            model_name='smsrisk',
            name='res_probability',
            field=models.CharField(blank=True, choices=[(b'5', b'5 - Bardzo wysokie'), (b'4', b'4 - Wysokie'), (b'3', b'3 - \xc5\x9arednie'), (b'2', b'2 - Niskie'), (b'1', b'1 - Bardzo niskie')], max_length=1, null=True, verbose_name=b'Szcz\xc4\x85tkowe prawdopodobie\xc5\x84stwo'),
        ),
        migrations.AlterField(
            model_name='smsrisk',
            name='smshazard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.SMSHazard', verbose_name=b'Zarejestrowane zagro\xc5\xbcenie'),
        ),
    ]
