# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import salt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        ('camo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blackout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Termin rozpoczęcia')),
                ('end_time', models.DateTimeField(verbose_name='Termin zakończenia')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('open_time', models.DateTimeField(auto_now_add=True, verbose_name='Termin utworzenia')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camo.Aircraft', verbose_name='Statek powietrzny')),
                ('open_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.FBOUser', verbose_name='Utworzone przez')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.BooleanField()),
            ],
            options={
                'permissions': [('res_user', 'REZERWACJE - Dostęp do modułu'), ('res_admin', 'REZERWACJE - Zarządzanie')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Termin rozpoczęcia')),
                ('end_time', models.DateTimeField(verbose_name='Termin zakończenia')),
                ('planned_type', models.CharField(choices=[('01', '01 - Przewóz lotniczy'), ('01A', '01A - Lot widokowy'), ('02', '02 - Operacje specjal.'), ('02H', '02H - Operacje specjal. HR'), ('03A', '03A - Szkolenie AOC'), ('03B', '03B - Szkolenie ATO'), ('03C', '03C - Szkolenie SPO'), ('03D', '03D - Lot zapoznawczy'), ('03E', '03E - Lot egzaminacyjny'), ('04', '04 - Wynajem SP'), ('05', '05 - Loty niepłatne'), ('06', '06 - Oblot techniczny'), ('06A', '06A - Sprawdzenie SP'), ('07', '07 - Lot prywatny')], max_length=3, verbose_name='Planowany rodzaj lotu')),
                ('planned_time', salt.models.MyDurationField(verbose_name='Planowany czas lotu')),
                ('loc_start', models.TextField(blank=True, default='EPMO', null=True, verbose_name='Lotnisko startu')),
                ('loc_stop', models.TextField(blank=True, null=True, verbose_name='Pierwszy odcinek')),
                ('loc_end', models.TextField(blank=True, null=True, verbose_name='Dalsze odcinki')),
                ('pax', models.TextField(blank=True, null=True, verbose_name='Lista pasażerów')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('internal_remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi SALT')),
                ('status', models.CharField(choices=[('Nowa', 'Nowa'), ('Potwierdzona', 'Potwierdzona'), ('Zrealizowana', 'Zrealizowana')], default='Nowa', max_length=12, verbose_name='Status rezerwacji')),
                ('open_time', models.DateTimeField(auto_now_add=True, verbose_name='Termin otwarcia')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='Termin ostatniej modyfikacji')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camo.Aircraft', verbose_name='Statek powietrzny')),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_changed_by_set', to='panel.FBOUser', verbose_name='Zmodyfikowana przez')),
                ('open_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_open_by_set', to='panel.FBOUser', verbose_name='Utworzona przez')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_owner_set', to='panel.Pilot', verbose_name='Właściciel rezerwacji')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_participant_set', to='panel.Pilot', verbose_name='Uczestnik rezerwacji')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationFBO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Termin rozpoczęcia')),
                ('end_time', models.DateTimeField(verbose_name='Termin zakończenia')),
                ('title', models.CharField(max_length=30, verbose_name='Tytuł rezerwacji')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('open_time', models.DateTimeField(auto_now_add=True, verbose_name='Termin otwarcia')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='Termin ostatniej modyfikacji')),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resfbo_changed_by_set', to='panel.FBOUser', verbose_name='Zmodyfikowana przez')),
                ('open_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resfbo_open_by_set', to='panel.FBOUser', verbose_name='Utworzona przez')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resfbo_owner_set', to='panel.FBOUser', verbose_name='Właściciel rezerwacji')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resfbo_participant_set', to='panel.FBOUser', verbose_name='Uczestnik rezerwacji')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceFBO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nazwa zasobu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis zasobu')),
                ('scheduled', models.BooleanField(default=True, verbose_name='Podlega rezerwacjom')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Informacje dla użytkownków')),
                ('color', models.CharField(default='#cdcdcd', max_length=7, verbose_name='Kolor wyświetlania')),
            ],
        ),
        migrations.AddField(
            model_name='reservationfbo',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.ResourceFBO', verbose_name='Rezerwowany zasób'),
        ),
    ]
