# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_auto_20161106_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackout',
            name='test',
            field=models.BooleanField(default=True, verbose_name='Test'),
        ),
    ]
