# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0004_blackout_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackout',
            name='test',
        ),
    ]
