# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 19:22
from __future__ import unicode_literals

from django.db import migrations, models
from datetime import timedelta
import salt.models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0005_remove_blackout_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='planned_time',
            field=salt.models.MyDurationField(default=timedelta(seconds=0), verbose_name='Planowany czas lotu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='planned_type',
            field=models.CharField(choices=[('01', '01 - Przewóz lotniczy'), ('01A', '01A - Lot widokowy'), ('02', '02 - Operacje specjal.'), ('02H', '02H - Operacje specjal. HR'), ('03A', '03A - Szkolenie AOC'), ('03B', '03B - Szkolenie ATO'), ('03C', '03C - Szkolenie SPO'), ('03D', '03D - Lot zapoznawczy'), ('03E', '03E - Lot egzaminacyjny'), ('04', '04 - Wynajem SP'), ('05', '05 - Loty niepłatne'), ('06', '06 - Oblot techniczny'), ('06A', '06A - Sprawdzenie SP'), ('07', '07 - Lot prywatny')], default='04', max_length=3, verbose_name='Planowany rodzaj lotu'),
            preserve_default=False,
        ),
    ]
