# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0044_duty_pdt'),
        ('res', '0006_auto_20161107_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationFBO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Termin rozpoczęcia')),
                ('end_time', models.DateTimeField(verbose_name='Termin zakończenia')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('open_time', models.DateTimeField(auto_now_add=True, verbose_name='Termin otwarcia')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='Termin ostatniej modyfikacji')),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resfbo_changed_by_set', to='panel.FBOUser', verbose_name='Zmodyfikowana przez')),
                ('open_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resfbo_open_by_set', to='panel.FBOUser', verbose_name='Utworzona przez')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resfbo_owner_set', to='panel.FBOUser', verbose_name='Właściciel rezerwacji')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resfbo_participant_set', to='panel.FBOUser', verbose_name='Uczestnik rezerwacji')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceFBO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nazwa zasobu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis zasobu')),
                ('scheduled', models.BooleanField(default=True, verbose_name='Podlega rezerwacjom')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Informacje dla użytkownków')),
                ('color', models.CharField(default='#ccffcc', max_length=7, verbose_name='Kolor wyświetlania')),
            ],
        ),
        migrations.AddField(
            model_name='reservationfbo',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.ResourceFBO', verbose_name='Rezerwowany zasób'),
        ),
    ]
