# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0007_auto_20161203_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationfbo',
            name='title',
            field=models.CharField(default='Test', max_length=30, verbose_name='Tytuł rezerwacji'),
            preserve_default=False,
        ),
    ]
