# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0009_auto_20161204_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='planned_route',
        ),
        migrations.AddField(
            model_name='reservation',
            name='loc_end',
            field=models.TextField(blank=True, null=True, verbose_name='Dalsze odcinki'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='loc_start',
            field=models.TextField(blank=True, null=True, verbose_name='Lotnisko startu'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='loc_stop',
            field=models.TextField(blank=True, null=True, verbose_name='Pierwszy odcinek'),
        ),
    ]
