# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0010_auto_20170112_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='loc_start',
            field=models.TextField(blank=True, default='EPMO', null=True, verbose_name='Lotnisko startu'),
        ),
    ]
