# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0011_auto_20170112_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_changed_by_set', to='panel.FBOUser', verbose_name='Zmodyfikowana przez'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_participant_set', to='panel.Pilot', verbose_name='Uczestnik rezerwacji'),
        ),
        migrations.AlterField(
            model_name='reservationfbo',
            name='change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resfbo_changed_by_set', to='panel.FBOUser', verbose_name='Zmodyfikowana przez'),
        ),
        migrations.AlterField(
            model_name='reservationfbo',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resfbo_participant_set', to='panel.FBOUser', verbose_name='Uczestnik rezerwacji'),
        ),
    ]
