# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0012_auto_20170115_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pax',
            field=models.TextField(blank=True, null=True, verbose_name='Lista pasażerów'),
        ),
    ]
