# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import salt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fin', '0001_initial'),
        ('camo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('company', models.CharField(choices=[('salt', 'SALT'), ('other', 'Poza SALT')], default='salt', max_length=10, verbose_name='Firma')),
                ('role', models.CharField(max_length=50, verbose_name='Stanowisko')),
                ('duty_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rodzaj obowiązków')),
                ('duty_time_from', models.TimeField(verbose_name='Rozpoczęcie służby')),
                ('duty_time_to', models.TimeField(verbose_name='Zakończenie służby')),
                ('duty_time', salt.models.MyDurationField(verbose_name='Czas służby')),
                ('fdp_time', salt.models.MyDurationField(blank=True, null=True, verbose_name='Czas czynności lotniczych')),
                ('block_time', salt.models.MyDurationField(blank=True, null=True, verbose_name='Czas lotu')),
                ('landings', models.IntegerField(blank=True, null=True, verbose_name='Liczba lądowań')),
                ('time_factor', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Mnożnik czasu')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='FBOUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('second_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adres email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon kontaktowy')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres linia 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres linia 2')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, verbose_name='Numer PESEL')),
                ('id_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Numer dowodu')),
                ('infos', models.BooleanField(default=False, verbose_name='Dostęp do INFOS')),
                ('mechanic', models.BooleanField(default=False, verbose_name='Mechanik')),
                ('module_ato', models.IntegerField(choices=[(0, 'Brak dostępu'), (1, 'Tylko odczyt'), (2, 'Pełen dostęp')], default=0, verbose_name='Moduł ATO')),
                ('module_camo', models.IntegerField(choices=[(0, 'Brak dostępu'), (1, 'Tylko odczyt'), (2, 'Pełen dostęp')], default=0, verbose_name='Moduł CAMO')),
                ('module_sms', models.IntegerField(choices=[(0, 'Brak dostępu'), (1, 'Tylko odczyt'), (2, 'Pełen dostęp'), (3, 'Dostęp NCR')], default=0, verbose_name='Moduł SMS')),
                ('module_fin', models.IntegerField(choices=[(0, 'Brak dostępu'), (1, 'Tylko odczyt'), (2, 'Pełny dostęp')], default=0, verbose_name='Moduł FIN')),
                ('module_res', models.IntegerField(choices=[(0, 'Brak dostępu'), (1, 'Tworzenie'), (2, 'Zarządzanie')], default=1, verbose_name='Moduł RES')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_no', models.IntegerField(blank=True, null=True, verbose_name='Nr. rejsu')),
                ('pax', models.IntegerField(blank=True, null=True, verbose_name='Liczba pasażerow')),
                ('bags', models.IntegerField(blank=True, null=True, verbose_name='Ciężar bagazu [kg]')),
                ('fuel_refill', models.IntegerField(default=0, verbose_name='Uzupełnione paliwo (L)')),
                ('fuel_source', models.CharField(default='unknown', max_length=10, verbose_name='Źródło paliwa')),
                ('fuel_available', models.IntegerField(verbose_name='Stan paliwa do lotu (L)')),
                ('fuel_used', models.IntegerField(blank=True, null=True, verbose_name='Paliwo zużyte (L)')),
                ('oil_refill', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Uzupełniony olej (qt)')),
                ('trans_oil_refill', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Uzup. olej przekł. (qt)')),
                ('hydr_oil_refill', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Uzup. olej hydr. (qt)')),
                ('loc_start', models.CharField(blank=True, max_length=20, null=True, verbose_name='Miejsce startu')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Czas off-block')),
                ('tth_start', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Licznik początkowy')),
                ('loc_end', models.CharField(blank=True, max_length=20, null=True, verbose_name='Miejsce lądowania')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Czas on-block')),
                ('tth_end', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Licznik końcowy')),
                ('landings', models.IntegerField(blank=True, default=0, null=True, verbose_name='Liczba lądowań')),
                ('cycles', models.IntegerField(blank=True, default=0, null=True, verbose_name='Liczba cykli')),
                ('status', models.CharField(choices=[('open', 'Otwarta'), ('closed', 'Zamknięta')], default='open', max_length=10, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='PDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_ref', models.IntegerField(verbose_name='Numer PDT')),
                ('flight_type', models.CharField(max_length=3, verbose_name='Rodzaj lotu')),
                ('date', models.DateField(verbose_name='Data PDT')),
                ('ext_voucher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Voucher obcy')),
                ('service_remarks', models.TextField(blank=True, null=True, verbose_name='Opis usługi')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('tth_start', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Licznik początkowy')),
                ('fuel_after', models.IntegerField(blank=True, null=True, verbose_name='Tankowanie po locie')),
                ('fuel_after_source', models.CharField(default='unknown', max_length=10, verbose_name='Źródło paliwa po locie')),
                ('prev_tth', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Suma TTH z przeniesienia')),
                ('prev_landings', models.IntegerField(blank=True, default=0, null=True, verbose_name='Suma lądowań z przeniesienia')),
                ('pre_cycles', models.IntegerField(blank=True, default=0, null=True, verbose_name='Suma cykli z przeniesienia')),
                ('failure_desc', models.TextField(blank=True, null=True, verbose_name='Opis usterki')),
                ('repair_desc', models.TextField(blank=True, null=True, verbose_name='Sposób usunięcia')),
                ('repair_time', models.DateTimeField(blank=True, null=True, verbose_name='Czas usunięcia')),
                ('status', models.CharField(choices=[('open', 'Otwarty'), ('closed', 'Zamknięty'), ('checked', 'Sprawdzony')], default='open', max_length=10, verbose_name='Status')),
                ('open_time', models.DateTimeField(auto_now_add=True, verbose_name='Czas otwarcia')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='Czas zamknięcia')),
                ('check_time', models.DateTimeField(blank=True, null=True, verbose_name='Czas sprawdzenia')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camo.Aircraft', verbose_name='Statek powietrzny')),
                ('check_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdt_checked_by_set', to='panel.FBOUser', verbose_name='Sprawdzony przez')),
                ('close_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdt_closed_by_set', to='panel.FBOUser', verbose_name='Zamknięty przez')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fin.Contractor', verbose_name='Kontrahent')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numer licencji')),
                ('licence_date', models.DateField(blank=True, null=True, verbose_name='Ważność licencji')),
                ('medical', models.CharField(blank=True, max_length=50, null=True, verbose_name='Badania lotnicze')),
                ('medical_date', models.DateField(blank=True, null=True, verbose_name='Ważność badań')),
                ('clearance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Upoważnienie SALT')),
                ('employee', models.BooleanField(default=False, verbose_name='Kontrola czasu pracy')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('fbouser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.FBOUser', verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='PilotAircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camo.Aircraft', verbose_name='Statek powietrzny')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Pilot', verbose_name='Pilot')),
            ],
        ),
        migrations.CreateModel(
            name='PilotFlightType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(max_length=3, verbose_name='Rodzaj lotu')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Pilot', verbose_name='Pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50, verbose_name='Nazwa uprawnienia')),
                ('valid_date', models.DateField(blank=True, null=True, verbose_name='Ważność uprawnienia')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Pilot', verbose_name='Pilot')),
            ],
        ),
        migrations.AddField(
            model_name='pdt',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdt_instr_set', to='panel.Pilot', verbose_name='Instruktor nadzorujący'),
        ),
        migrations.AddField(
            model_name='pdt',
            name='ms_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camo.MS_report', verbose_name='Na podstawie MS'),
        ),
        migrations.AddField(
            model_name='pdt',
            name='next_pdt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_pdt', to='panel.PDT', verbose_name='Następny PDT dla SP'),
        ),
        migrations.AddField(
            model_name='pdt',
            name='open_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdt_open_by_set', to='panel.FBOUser', verbose_name='Otwarty przez'),
        ),
        migrations.AddField(
            model_name='pdt',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdt_pic_set', to='panel.Pilot', verbose_name='Pierwszy pilot'),
        ),
        migrations.AddField(
            model_name='pdt',
            name='reapair_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdt_repaired_by_set', to='panel.FBOUser', verbose_name='Usunięta przez'),
        ),
    ]
