# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fin', '0002_auto_20170612_2321'),
        ('panel', '0001_initial'),
        ('ato', '0002_auto_20170612_2321'),
        ('res', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdt',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.Reservation', verbose_name='Na podstawie rezerwacji'),
        ),
        migrations.AddField(
            model_name='pdt',
            name='sic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdt_sic_set', to='panel.Pilot', verbose_name='Drugi pilot'),
        ),
        migrations.AddField(
            model_name='pdt',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ato.Training_inst', verbose_name='Szkolenie'),
        ),
        migrations.AddField(
            model_name='pdt',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fin.Voucher', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='operation',
            name='pdt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.PDT'),
        ),
        migrations.AddField(
            model_name='fbouser',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fin.Contractor', verbose_name='Kontrahent'),
        ),
        migrations.AddField(
            model_name='fbouser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='duty',
            name='pdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.PDT'),
        ),
        migrations.AddField(
            model_name='duty',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Pilot'),
        ),
    ]
