# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20170612_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['operation_no']},
        ),
        migrations.AddField(
            model_name='fbouser',
            name='ncr_user',
            field=models.BooleanField(default=False, verbose_name='Odpowiedzialny w NCR'),
        ),
    ]
