# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import salt.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20170807_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='duty_time',
            field=salt.models.MyDurationField(verbose_name='Czas łączny'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='duty_time_from',
            field=models.TimeField(verbose_name='Rozpoczęcie'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='duty_time_to',
            field=models.TimeField(verbose_name='Zakończenie'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='fdp_time',
            field=salt.models.MyDurationField(blank=True, null=True, verbose_name='Czas czynności'),
        ),
    ]
