# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0006_auto_20161107_2022'),
        ('panel', '0040_fbouser_module_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdt',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='res.Reservation', verbose_name='Na podstawie rezerwacji'),
        ),
    ]
