# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0041_pdt_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='role',
            field=models.CharField(default='Nieokreślone', max_length=50, verbose_name='Stanowisko'),
            preserve_default=False,
        ),
    ]
