# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0042_auto_20161113_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='duty_time_from',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Rozpoczęcie służby'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duty',
            name='duty_time_to',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Zakończenie służby'),
            preserve_default=False,
        ),
    ]
