# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0044_duty_pdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbouser',
            name='infos',
            field=models.BooleanField(default=False, verbose_name='Dostęp do INFOS'),
        ),
    ]
