# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0045_fbouser_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdt',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.Reservation', verbose_name='Na podstawie rezerwacji'),
        ),
    ]
