# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0048_auto_20170312_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='tth_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Licznik początkowy'),
        ),
    ]
