# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0049_auto_20170418_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdt',
            name='next_pdt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_pdt', to='panel.PDT', verbose_name='Następny PDT dla SP'),
        ),
    ]
