# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0050_pdt_next_pdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbouser',
            name='mechanic',
            field=models.BooleanField(default=False, verbose_name='Mechanik'),
        ),
        migrations.AlterField(
            model_name='pdt',
            name='fuel_after',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tankowanie po locie'),
        ),
        migrations.AlterField(
            model_name='pdt',
            name='next_pdt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_pdt', to='panel.PDT', verbose_name='Następny PDT dla SP'),
        ),
    ]
