# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0052_auto_20170613_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbouser',
            name='ncr_user',
            field=models.BooleanField(default=False, verbose_name='Osoba odpowiedzialna za NCR'),
        ),
    ]
