# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import salt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='Kod ćwiczenia')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa ćwiczenia')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis ćwiczenia')),
                ('restrictions', models.CharField(choices=[('TAK', 'TAK'), ('NIE', 'NIE')], default='NIE', max_length=3, verbose_name='Restrykcje na instruktora')),
                ('min_time_instr', salt.models.MyDurationField(blank=True, null=True, verbose_name='Min. czas z instr.')),
                ('min_time_solo', salt.models.MyDurationField(blank=True, null=True, verbose_name='Min. czas solo')),
                ('min_num_instr', models.IntegerField(blank=True, null=True, verbose_name='Min. liczba powtórzeń z instr.')),
                ('min_num_solo', models.IntegerField(blank=True, null=True, verbose_name='Min. liczba powtórzeń solo')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_inst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='Kod ćwiczenia')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa ćwiczenia')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis ćwiczenia')),
                ('restrictions', models.CharField(choices=[('TAK', 'TAK'), ('NIE', 'NIE')], default='NIE', max_length=3, verbose_name='Restrykcje na instruktora')),
                ('min_time_instr', salt.models.MyDurationField(blank=True, null=True, verbose_name='Min. czas z instr.')),
                ('min_time_solo', salt.models.MyDurationField(blank=True, null=True, verbose_name='Min. czas solo')),
                ('min_num_instr', models.IntegerField(blank=True, null=True, verbose_name='Min. liczba powtórzeń z instr.')),
                ('min_num_solo', models.IntegerField(blank=True, null=True, verbose_name='Min. liczba powtórzeń solo')),
                ('time_instr', salt.models.MyDurationField(blank=True, null=True, verbose_name='Czas z instr.')),
                ('time_solo', salt.models.MyDurationField(blank=True, null=True, verbose_name='Czas solo')),
                ('num_instr', models.IntegerField(default=0, verbose_name='Liczba powtórzeń z instr.')),
                ('num_solo', models.IntegerField(default=0, verbose_name='Liczba powtórzeń solo')),
                ('passed', models.CharField(choices=[('TAK', 'TAK'), ('NIE', 'NIE')], default='NIE', max_length=3, verbose_name='Zaliczenie')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_oper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solo', models.BooleanField(default=False, verbose_name='Lot solo')),
                ('time_allocated', salt.models.MyDurationField(default=datetime.timedelta(0), verbose_name='Czas ćwiczenia')),
                ('num_allocated', models.IntegerField(default=0, verbose_name='Liczba powtórzeń ćwiczenia')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrictions', models.CharField(choices=[('TAK', 'TAK'), ('NIE', 'NIE')], default='NIE', max_length=3, verbose_name='Restrykcje')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.BooleanField()),
            ],
            options={
                'permissions': [('ato_reader', 'ATO - Dostęp do odczytu'), ('ato_admin', 'ATO - Dostęp pełny')],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='Kod zadania/fazy')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa zadania/fazy')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis zadania/fazy')),
                ('min_time_instr', salt.models.MyDurationField(blank=True, null=True, verbose_name='Min. czas z instr.')),
                ('min_time_solo', salt.models.MyDurationField(blank=True, null=True, verbose_name='Min. czas solo')),
            ],
        ),
        migrations.CreateModel(
            name='Phase_inst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='Kod zadania/fazy')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa zadania/fazy')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis zadania/fazy')),
                ('min_time_instr', salt.models.MyDurationField(blank=True, null=True, verbose_name='Min. czas z instr.')),
                ('min_time_solo', salt.models.MyDurationField(blank=True, null=True, verbose_name='Min. czas solo')),
                ('passed', models.CharField(choices=[('TAK', 'TAK'), ('NIE', 'NIE')], default='NIE', max_length=3, verbose_name='Zaliczenie')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Kod szkolenia')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa szkolenia')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data wprowadenia programu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis szkolenia')),
            ],
        ),
        migrations.CreateModel(
            name='Training_inst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('passed', models.CharField(choices=[('TAK', 'TAK'), ('NIE', 'NIE')], default='NIE', max_length=3, verbose_name='Ukończone')),
                ('pass_date', models.DateField(blank=True, null=True, verbose_name='Data ukończenia')),
                ('open', models.BooleanField(default=True, verbose_name='Czy otwarte')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Instructor', verbose_name='Instruktor prowadzący')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Student', verbose_name='Student')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Training', verbose_name='Szkolenie')),
            ],
        ),
    ]
