# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        ('ato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pilot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.Pilot', verbose_name='Pilot'),
        ),
        migrations.AddField(
            model_name='phase_inst',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ato.Phase_inst', verbose_name='Wymagane poprzednie zdanie/faza'),
        ),
        migrations.AddField(
            model_name='phase_inst',
            name='training_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Training_inst', verbose_name='Szkolenie'),
        ),
        migrations.AddField(
            model_name='phase',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ato.Phase', verbose_name='Wymagane poprzednie zdanie/faza'),
        ),
        migrations.AddField(
            model_name='phase',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Training', verbose_name='Szkolenie'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='pilot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.Pilot', verbose_name='Pilot'),
        ),
        migrations.AddField(
            model_name='exercise_oper',
            name='exercise_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Exercise_inst', verbose_name='Cwiczenie'),
        ),
        migrations.AddField(
            model_name='exercise_oper',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Operation', verbose_name='Operacja'),
        ),
        migrations.AddField(
            model_name='exercise_inst',
            name='phase_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Phase_inst', verbose_name='Zadanie/faza'),
        ),
        migrations.AddField(
            model_name='exercise_inst',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ato.Exercise_inst', verbose_name='Wymagane poprzednie ćwiczenie'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Phase', verbose_name='Zadanie/faza'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ato.Exercise', verbose_name='Wymagane poprzednie ćwiczenie'),
        ),
    ]
