# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 18:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import salt.models


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0002_auto_20170612_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data lotów')),
                ('pdt_num', models.CharField(blank=True, max_length=12, null=True, verbose_name='Numer PDT')),
                ('dual_time', salt.models.MyDurationField(default=datetime.timedelta(0), verbose_name='Czas dwuster')),
                ('dual_num', models.IntegerField(default=0, verbose_name='Liczba powtórzeń dwuster')),
                ('solo_time', salt.models.MyDurationField(default=datetime.timedelta(0), verbose_name='Czas solo')),
                ('solo_num', models.IntegerField(default=0, verbose_name='Liczba powtórzeń solo')),
                ('passed', models.IntegerField(choices=[(0, 'Kontynuacja'), (1, 'Zaliczenie')], default=0, verbose_name='Zaliczenie')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('internal_remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi dla instruktorów')),
                ('exercise_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Exercise_inst', verbose_name='Cwiczenie')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Instructor', verbose_name='Instructor')),
                ('training_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ato.Training_inst', verbose_name='Szkolenie')),
            ],
        ),
    ]
