# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0043_auto_20180513_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_entry',
            name='passed',
            field=models.BooleanField(choices=[(False, b'Kontynuacja'), (True, b'Zaliczenie')], default=False, verbose_name=b'Zaliczenie'),
        ),
    ]
