# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0044_auto_20180515_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_entry',
            name='passed',
            field=models.IntegerField(choices=[(0, b'Kontynuacja'), (1, b'Zaliczenie')], default=False, verbose_name=b'Zaliczenie'),
        ),
    ]
