# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data operacji')),
                ('type', models.CharField(choices=[('Wpłata', 'Wpłata'), ('Wypłata', 'Wypłata'), ('Korekta', 'Korekta'), ('Usługa AOC', 'Usługa AOC'), ('Usługa SPO', 'Usługa SPO'), ('Wynajem', 'Wynajem'), ('Szkolenie', 'Szkolenie'), ('Egzamin', 'Egzamin'), ('Instruktor', 'Instruktor'), ('Zakup pakietu', 'Zakup pakietu'), ('Zwrot za pakiet', 'Zwrot za pakiet'), ('Zwrot za paliwo', 'Zwrot za paliwo')], max_length=15, verbose_name='Rodzaj operacji')),
                ('document', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dokument operacji')),
                ('ato_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Kwota operacji (szkolenia)')),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Kwota operacji (wynajem)')),
                ('aoc_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Kwota operacji (AOC)')),
                ('spo_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Kwota operacji (SPO)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.CharField(max_length=20, verbose_name='Identyfikator FK')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kontrahenta')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres kontrahenta')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres kontrahenta')),
                ('company', models.BooleanField(default=False, verbose_name='Firma')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, verbose_name='Numer PESEL')),
                ('nip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numer NIP')),
                ('regon', models.CharField(blank=True, max_length=9, null=True, verbose_name='Numer REGON')),
                ('active', models.BooleanField(default=True, verbose_name='Czy aktywny?')),
                ('ato_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Saldo szkoleń')),
                ('rent_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Saldo wynajmu')),
                ('aoc_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Saldo AOC')),
                ('spo_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Saldo usług')),
                ('debet_allowed', models.BooleanField(default=False, verbose_name='Zgoda na debet')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='FuelCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data protokołu różnic')),
                ('document', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dokument protokołu różnic')),
                ('fuel_volume', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Objętość różnicy (L)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='FuelDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data dostawy')),
                ('provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dostawca paliwa')),
                ('document', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dokument dostawy')),
                ('fuel_volume', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Objętość paliwa (L)')),
                ('liter_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena za litr (PLN)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='FuelTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_ref', models.CharField(max_length=10, verbose_name='Symbol zbiornika')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa zbiornika')),
                ('fuel_type', models.CharField(choices=[('AVGAS', 'Avgas 100LL'), ('MOGAS', 'Benzyna samochodowa'), ('JETA1', 'Paliwo JET A-1')], max_length=5, verbose_name='Rodzaj paliwa')),
                ('fuel_volume', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Objętość paliwa (L)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='FuelTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data wydania wew.')),
                ('document', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dokument wydania wew.')),
                ('fuel_volume', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Objętość paliwa (L)')),
                ('liter_price', models.FloatField(verbose_name='Średnia cena za litr (PLN)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='LocalFueling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data tankowania')),
                ('person', models.CharField(blank=True, max_length=50, null=True, verbose_name='Osoba tankująca')),
                ('fuel_volume', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Objętość paliwa (L)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.BooleanField()),
            ],
            options={
                'permissions': [('fin_reader', 'FIN - Dostęp do odczytu'), ('fin_admin', 'FIN - Dostęp pełny')],
            },
        ),
        migrations.CreateModel(
            name='PDTFueling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_volume', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Objętość paliwa (L)')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteFueling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='Lotnisko tankowania')),
                ('fuel_volume', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Objętość paliwa (L)')),
                ('document', models.CharField(blank=True, max_length=30, null=True, verbose_name='Faktura za tankowanie')),
                ('excise', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dowód dostawy')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Wartość paliwa (PLN)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='RentPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=20, verbose_name='Identyfikator pakietu')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa pakietu')),
                ('ac_type', models.CharField(max_length=50, verbose_name='Typ SP')),
                ('hours', models.IntegerField(verbose_name='Liczba godzin')),
                ('hour_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena za godzinę')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='SoldPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data zakupu pakietu')),
                ('package_id', models.CharField(max_length=20, verbose_name='Identyfikator pakietu')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa pakietu')),
                ('ac_type', models.CharField(max_length=50, verbose_name='Typ SP')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Liczba godzin')),
                ('left_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pozostała liczba godzin')),
                ('hour_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena za godzinę')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.Contractor', verbose_name='Kontrahent')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_type', models.CharField(max_length=50, verbose_name='Typ SP')),
                ('hour_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena za godzinę')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.Contractor', verbose_name='Kontrahent')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_id', models.CharField(max_length=20, verbose_name='Identyfikator')),
                ('voucher_code', models.CharField(max_length=10, verbose_name='Kod vouchera')),
                ('persons', models.IntegerField(verbose_name='Liczba osób')),
                ('time', models.IntegerField(verbose_name='Czas trwania (min)')),
                ('description', models.CharField(max_length=100, verbose_name='Opis vouchera')),
                ('issue_date', models.DateField(verbose_name='Data sprzedaży')),
                ('valid_date', models.DateField(verbose_name='Data ważności')),
                ('payment', models.CharField(choices=[('cash', 'Gotówka'), ('transfer', 'Przelew bankowy'), ('epay', 'Płatność elektroniczna')], max_length=10, verbose_name='Forma płatności')),
                ('paid', models.BooleanField(default=False, verbose_name='Opłacony')),
                ('done_date', models.DateField(blank=True, null=True, verbose_name='Data realizacji')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
            ],
        ),
    ]
