# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        ('camo', '0002_auto_20170612_2321'),
        ('fin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotefueling',
            name='pdt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.PDT', verbose_name='PDT'),
        ),
        migrations.AddField(
            model_name='pdtfueling',
            name='fueltank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.FuelTank', verbose_name='Zbiornik paliwa'),
        ),
        migrations.AddField(
            model_name='pdtfueling',
            name='pdt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.PDT', verbose_name='PDT'),
        ),
        migrations.AddField(
            model_name='localfueling',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camo.Aircraft', verbose_name='Statek powietrzny'),
        ),
        migrations.AddField(
            model_name='localfueling',
            name='fueltank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.FuelTank', verbose_name='Zbiornik paliwa'),
        ),
        migrations.AddField(
            model_name='fueltransfer',
            name='fueltank_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_transfers', to='fin.FuelTank', verbose_name='Zbiornik żródłowy'),
        ),
        migrations.AddField(
            model_name='fueltransfer',
            name='fueltank_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_transfers', to='fin.FuelTank', verbose_name='Zbiornik docelowy'),
        ),
        migrations.AddField(
            model_name='fueldelivery',
            name='fueltank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.FuelTank', verbose_name='Zbiornik paliwa'),
        ),
        migrations.AddField(
            model_name='fuelcorrection',
            name='fueltank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.FuelTank', verbose_name='Zbiornik paliwa'),
        ),
        migrations.AddField(
            model_name='balanceoperation',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.Contractor', verbose_name='Kontrahent'),
        ),
        migrations.AddField(
            model_name='balanceoperation',
            name='pdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.PDT', verbose_name='Powiązany PDT'),
        ),
    ]
