# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0020_auto_20160403_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperation',
            name='pdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.PDT', verbose_name='Powiązany PDT'),
        ),
    ]
