# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0021_auto_20170115_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperation',
            name='pdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.PDT', verbose_name=b'Powi\xc4\x85zany PDT'),
        ),
        migrations.AlterField(
            model_name='balanceoperation',
            name='type',
            field=models.CharField(choices=[(b'Wp\xc5\x82ata', b'Wp\xc5\x82ata'), (b'Wyp\xc5\x82ata', b'Wyp\xc5\x82ata'), (b'Korekta', b'Korekta'), (b'Us\xc5\x82uga AOC', b'Us\xc5\x82uga AOC'), (b'Us\xc5\x82uga SPO', b'Us\xc5\x82uga SPO'), (b'Wynajem', b'Wynajem'), (b'Szkolenie', b'Szkolenie'), (b'Egzamin', b'Egzamin'), (b'Instruktor', b'Instruktor'), (b'Zakup pakietu', b'Zakup pakietu'), (b'Zwrot za pakiet', b'Zwrot za pakiet'), (b'Zwrot za paliwo', b'Zwrot za paliwo')], max_length=15, verbose_name=b'Rodzaj operacji'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='ato_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name=b'Saldo szkole\xc5\x84'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='spo_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name=b'Saldo us\xc5\x82ug'),
        ),
        migrations.AlterField(
            model_name='fuelcorrection',
            name='date',
            field=models.DateField(verbose_name=b'Data protoko\xc5\x82u r\xc3\xb3\xc5\xbcnic'),
        ),
        migrations.AlterField(
            model_name='fuelcorrection',
            name='document',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Dokument protoko\xc5\x82u r\xc3\xb3\xc5\xbcnic'),
        ),
        migrations.AlterField(
            model_name='fuelcorrection',
            name='fuel_volume',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name=b'Obj\xc4\x99to\xc5\x9b\xc4\x87 r\xc3\xb3\xc5\xbcnicy (L)'),
        ),
        migrations.AlterField(
            model_name='fueldelivery',
            name='fuel_volume',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name=b'Obj\xc4\x99to\xc5\x9b\xc4\x87 paliwa (L)'),
        ),
        migrations.AlterField(
            model_name='fueltank',
            name='fuel_volume',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name=b'Obj\xc4\x99to\xc5\x9b\xc4\x87 paliwa (L)'),
        ),
        migrations.AlterField(
            model_name='fueltransfer',
            name='fuel_volume',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name=b'Obj\xc4\x99to\xc5\x9b\xc4\x87 paliwa (L)'),
        ),
        migrations.AlterField(
            model_name='fueltransfer',
            name='fueltank_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_transfers', to='fin.FuelTank', verbose_name=b'Zbiornik \xc5\xbcr\xc3\xb3d\xc5\x82owy'),
        ),
        migrations.AlterField(
            model_name='fueltransfer',
            name='liter_price',
            field=models.FloatField(verbose_name=b'\xc5\x9arednia cena za litr (PLN)'),
        ),
        migrations.AlterField(
            model_name='localfueling',
            name='fuel_volume',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name=b'Obj\xc4\x99to\xc5\x9b\xc4\x87 paliwa (L)'),
        ),
        migrations.AlterField(
            model_name='localfueling',
            name='person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Osoba tankuj\xc4\x85ca'),
        ),
        migrations.AlterField(
            model_name='pdtfueling',
            name='fuel_volume',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name=b'Obj\xc4\x99to\xc5\x9b\xc4\x87 paliwa (L)'),
        ),
        migrations.AlterField(
            model_name='remotefueling',
            name='excise',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Dow\xc3\xb3d dostawy'),
        ),
        migrations.AlterField(
            model_name='remotefueling',
            name='fuel_volume',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name=b'Obj\xc4\x99to\xc5\x9b\xc4\x87 paliwa (L)'),
        ),
        migrations.AlterField(
            model_name='remotefueling',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'Warto\xc5\x9b\xc4\x87 paliwa (PLN)'),
        ),
        migrations.AlterField(
            model_name='rentpackage',
            name='hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name=b'Cena za godzin\xc4\x99'),
        ),
        migrations.AlterField(
            model_name='soldpackage',
            name='hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name=b'Cena za godzin\xc4\x99'),
        ),
        migrations.AlterField(
            model_name='soldpackage',
            name='left_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Pozosta\xc5\x82a liczba godzin'),
        ),
        migrations.AlterField(
            model_name='specialprice',
            name='hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name=b'Cena za godzin\xc4\x99'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='issue_date',
            field=models.DateField(verbose_name=b'Data sprzeda\xc5\xbcy'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='paid',
            field=models.BooleanField(default=False, verbose_name=b'Op\xc5\x82acony'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='payment',
            field=models.CharField(choices=[(b'cash', b'Got\xc3\xb3wka'), (b'transfer', b'Przelew bankowy'), (b'epay', b'P\xc5\x82atno\xc5\x9b\xc4\x87 elektroniczna')], max_length=10, verbose_name=b'Forma p\xc5\x82atno\xc5\x9bci'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='persons',
            field=models.IntegerField(verbose_name=b'Liczba os\xc3\xb3b'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_date',
            field=models.DateField(verbose_name=b'Data wa\xc5\xbcno\xc5\x9bci'),
        ),
    ]
