# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='info_contact',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='info_body',
            field=models.TextField(blank=True, null=True, verbose_name='Pozstałe informacje'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='info_priority',
            field=models.TextField(blank=True, null=True, verbose_name='Ważne informacje'),
        ),
    ]
