# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbo', '0002_auto_20170424_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='info_body',
            field=models.TextField(blank=True, null=True, verbose_name='Pozostałe informacje'),
        ),
    ]
