# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbo', '0003_auto_20170514_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='info_body',
            field=models.TextField(blank=True, null=True, verbose_name=b'Pozosta\xc5\x82e informacje'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='info_priority',
            field=models.TextField(blank=True, null=True, verbose_name=b'Wa\xc5\xbcne informacje'),
        ),
    ]
